# Numpy

In [2]:
# Numpy contain HOMOGENIOUS data ---> mean each element must be of same type

In [3]:
import numpy as np

In [11]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
type(x)

numpy.ndarray

In [13]:
x.size

16

In [14]:
x.shape

(16,)

In [15]:
x.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
x.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [17]:
x.reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [19]:
z = np.arange(36)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [20]:
z.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [21]:
z.reshape(2,3,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [23]:
z.reshape(2,3,3,2)

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]]])

In [25]:
zz = np.arange(144)
zz

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143])

In [26]:
zz.reshape(12,12)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131],
       [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143]])

In [27]:
zz.reshape(2,6,12)

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131],
        [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143]]])

In [28]:
zz.reshape(3,4,6,2)

array([[[[  0,   1],
         [  2,   3],
         [  4,   5],
         [  6,   7],
         [  8,   9],
         [ 10,  11]],

        [[ 12,  13],
         [ 14,  15],
         [ 16,  17],
         [ 18,  19],
         [ 20,  21],
         [ 22,  23]],

        [[ 24,  25],
         [ 26,  27],
         [ 28,  29],
         [ 30,  31],
         [ 32,  33],
         [ 34,  35]],

        [[ 36,  37],
         [ 38,  39],
         [ 40,  41],
         [ 42,  43],
         [ 44,  45],
         [ 46,  47]]],


       [[[ 48,  49],
         [ 50,  51],
         [ 52,  53],
         [ 54,  55],
         [ 56,  57],
         [ 58,  59]],

        [[ 60,  61],
         [ 62,  63],
         [ 64,  65],
         [ 66,  67],
         [ 68,  69],
         [ 70,  71]],

        [[ 72,  73],
         [ 74,  75],
         [ 76,  77],
         [ 78,  79],
         [ 80,  81],
         [ 82,  83]],

        [[ 84,  85],
         [ 86,  87],
         [ 88,  89],
         [ 90,  91],
         [ 92,  93

In [29]:
zz.reshape(3,2,2,2,3,2)

array([[[[[[  0,   1],
           [  2,   3],
           [  4,   5]],

          [[  6,   7],
           [  8,   9],
           [ 10,  11]]],


         [[[ 12,  13],
           [ 14,  15],
           [ 16,  17]],

          [[ 18,  19],
           [ 20,  21],
           [ 22,  23]]]],



        [[[[ 24,  25],
           [ 26,  27],
           [ 28,  29]],

          [[ 30,  31],
           [ 32,  33],
           [ 34,  35]]],


         [[[ 36,  37],
           [ 38,  39],
           [ 40,  41]],

          [[ 42,  43],
           [ 44,  45],
           [ 46,  47]]]]],




       [[[[[ 48,  49],
           [ 50,  51],
           [ 52,  53]],

          [[ 54,  55],
           [ 56,  57],
           [ 58,  59]]],


         [[[ 60,  61],
           [ 62,  63],
           [ 64,  65]],

          [[ 66,  67],
           [ 68,  69],
           [ 70,  71]]]],



        [[[[ 72,  73],
           [ 74,  75],
           [ 76,  77]],

          [[ 78,  79],
           [ 80,  81],
           

In [31]:
# if we want to make some changes then we do this 

y = x.reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
y[1]  # 2nd-row

array([4, 5, 6, 7])

In [34]:
y[:,1]  # 2nd-column 

array([ 1,  5,  9, 13])

In [36]:
y[1:,::2]

array([[ 4,  6],
       [ 8, 10],
       [12, 14]])

In [37]:
y[1:,::2]=-99

In [38]:
y

array([[  0,   1,   2,   3],
       [-99,   5, -99,   7],
       [-99,   9, -99,  11],
       [-99,  13, -99,  15]])

In [39]:
y.max()

15

In [40]:
y.max(axis=0) # column wise max value

array([ 0, 13,  2, 15])

In [42]:
y.max(axis=1) # row wise max values

array([ 3,  7, 11, 15])

In [50]:
# writing both function in one line


np.arange(64).reshape(8,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [46]:
np.zeros((4,4))   # must remenber that argument must pass in form of tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.empty([2,4,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [54]:
np.full([2,3],33)

array([[33, 33, 33],
       [33, 33, 33]])

In [55]:
np.full([4,5],66)

array([[66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66]])

In [56]:
np.full([6,6],-9)

array([[-9, -9, -9, -9, -9, -9],
       [-9, -9, -9, -9, -9, -9],
       [-9, -9, -9, -9, -9, -9],
       [-9, -9, -9, -9, -9, -9],
       [-9, -9, -9, -9, -9, -9],
       [-9, -9, -9, -9, -9, -9]])

In [58]:
ls = ['python',3,2,'java',3.3]
ls = np.array(ls)
ls

array(['python', '3', '2', 'java', '3.3'], dtype='<U32')

In [59]:
ls[0]

'python'

In [60]:
type(ls)

numpy.ndarray

In [64]:
ls[:-1]

array(['python', '3', '2', 'java'], dtype='<U32')

In [67]:
z.ndim

1

In [70]:
# np.arange(start,stop,number of dimention)
a = np.arange(6,12,1).reshape(2,3)
a

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
b = np.arange(6,12,1).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [72]:
a*b

array([[ 36,  49,  64],
       [ 81, 100, 121]])

In [73]:
a>b

array([[False, False, False],
       [False, False, False]])

In [74]:
a+3

array([[ 9, 10, 11],
       [12, 13, 14]])

In [77]:
a[a%3==True]   # to check the remainder in numbers

array([ 7, 10])

In [78]:
values = np.random.randn(3,3)

In [79]:
values

array([[-0.08913454, -2.67484768,  0.6559318 ],
       [ 1.25446721, -1.62396917, -0.16421191],
       [ 0.15252921,  1.01492961, -1.78629654]])

In [80]:
pets = np.array([['cat','dog','cat'],['dog','dog','cat'],
                ['dog','cat','dog']])
pets

array([['cat', 'dog', 'cat'],
       ['dog', 'dog', 'cat'],
       ['dog', 'cat', 'dog']], dtype='<U3')

In [82]:
values[pets=='cat']

array([-0.08913454,  0.6559318 , -0.16421191,  1.01492961])

In [84]:
arr = np.random.randn(10,10)
arr

array([[ 1.64710178, -0.27787032,  0.43526208, -0.79284208,  1.01402563,
         0.60835009, -0.72480832,  0.5638098 ,  0.74524684,  0.45602785],
       [ 2.15115609, -0.86739663, -1.39067498,  0.10963273,  2.14843676,
         0.97228649, -1.14042778,  0.87840106, -0.0266013 , -0.12343259],
       [ 0.11659293, -1.99000376,  0.18051052,  0.50918594,  0.82530421,
        -0.58359072, -0.75205777, -0.64818406, -0.91151459, -1.58098691],
       [ 0.16841022, -0.35920354, -2.19141482,  0.62866897,  1.14304069,
        -0.71113308,  0.50998796,  0.29732594,  0.04582597, -1.08123164],
       [ 0.57524444, -0.60274953,  0.42640201, -0.99218745, -0.93223546,
         0.65815461, -0.69374119,  0.08187935, -0.59157353,  0.51507118],
       [ 0.3716624 , -0.82278943, -1.99253912, -0.02370669, -0.14428667,
         0.874091  , -1.11212803,  1.11881773,  0.31271097,  0.36947522],
       [-0.98232842,  0.51970319, -0.28401729,  1.23163955, -0.41617817,
         0.05053726, -0.42424557,  0.18849547

In [87]:
arr = arr.round(2)
arr

array([[ 1.65, -0.28,  0.44, -0.79,  1.01,  0.61, -0.72,  0.56,  0.75,
         0.46],
       [ 2.15, -0.87, -1.39,  0.11,  2.15,  0.97, -1.14,  0.88, -0.03,
        -0.12],
       [ 0.12, -1.99,  0.18,  0.51,  0.83, -0.58, -0.75, -0.65, -0.91,
        -1.58],
       [ 0.17, -0.36, -2.19,  0.63,  1.14, -0.71,  0.51,  0.3 ,  0.05,
        -1.08],
       [ 0.58, -0.6 ,  0.43, -0.99, -0.93,  0.66, -0.69,  0.08, -0.59,
         0.52],
       [ 0.37, -0.82, -1.99, -0.02, -0.14,  0.87, -1.11,  1.12,  0.31,
         0.37],
       [-0.98,  0.52, -0.28,  1.23, -0.42,  0.05, -0.42,  0.19,  2.19,
         1.44],
       [ 0.2 ,  0.02,  1.85, -1.48, -0.68,  0.55,  0.65, -0.8 , -0.08,
        -0.26],
       [ 0.1 ,  0.08,  0.12,  0.7 ,  1.03,  1.27, -0.97, -0.77, -0.23,
         2.2 ],
       [-0.6 ,  1.26,  0.63,  0.37,  0.51,  0.54,  1.37, -0.85,  0.47,
        -1.46]])

In [88]:
print(np.round(arr,2))

[[ 1.65 -0.28  0.44 -0.79  1.01  0.61 -0.72  0.56  0.75  0.46]
 [ 2.15 -0.87 -1.39  0.11  2.15  0.97 -1.14  0.88 -0.03 -0.12]
 [ 0.12 -1.99  0.18  0.51  0.83 -0.58 -0.75 -0.65 -0.91 -1.58]
 [ 0.17 -0.36 -2.19  0.63  1.14 -0.71  0.51  0.3   0.05 -1.08]
 [ 0.58 -0.6   0.43 -0.99 -0.93  0.66 -0.69  0.08 -0.59  0.52]
 [ 0.37 -0.82 -1.99 -0.02 -0.14  0.87 -1.11  1.12  0.31  0.37]
 [-0.98  0.52 -0.28  1.23 -0.42  0.05 -0.42  0.19  2.19  1.44]
 [ 0.2   0.02  1.85 -1.48 -0.68  0.55  0.65 -0.8  -0.08 -0.26]
 [ 0.1   0.08  0.12  0.7   1.03  1.27 -0.97 -0.77 -0.23  2.2 ]
 [-0.6   1.26  0.63  0.37  0.51  0.54  1.37 -0.85  0.47 -1.46]]


In [94]:
print(arr[0:10:2,::])

[[ 1.65 -0.28  0.44 -0.79  1.01  0.61 -0.72  0.56  0.75  0.46]
 [ 0.12 -1.99  0.18  0.51  0.83 -0.58 -0.75 -0.65 -0.91 -1.58]
 [ 0.58 -0.6   0.43 -0.99 -0.93  0.66 -0.69  0.08 -0.59  0.52]
 [-0.98  0.52 -0.28  1.23 -0.42  0.05 -0.42  0.19  2.19  1.44]
 [ 0.1   0.08  0.12  0.7   1.03  1.27 -0.97 -0.77 -0.23  2.2 ]]


In [96]:
# np.maximum()  ---> compare corresponding values 

p = np.array([2,3,4,1,23,43])  
q = np.array([25,6,6,1,23,43])

In [97]:
np.maximum(p,q)

array([25,  6,  6,  1, 23, 43])

### Algebra related

In [101]:
k = np.arange(12).reshape(3,4)
l = np.arange(12).reshape(4,3)
print(k)
print(l)
np.dot(k,l)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [102]:
x.T

array([  0,   1,   2,   3, -99,   5, -99,   7, -99,   9, -99,  11, -99,
        13, -99,  15])

In [103]:
y

array([[  0,   1,   2,   3],
       [-99,   5, -99,   7],
       [-99,   9, -99,  11],
       [-99,  13, -99,  15]])

In [104]:
y.T

array([[  0, -99, -99, -99],
       [  1,   5,   9,  13],
       [  2, -99, -99, -99],
       [  3,   7,  11,  15]])

In [106]:
y.flatten()  # it convert every thing into one dimentional array

array([  0,   1,   2,   3, -99,   5, -99,   7, -99,   9, -99,  11, -99,
        13, -99,  15])

In [121]:
a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(3,2)

print(a)
print('*'*12)
print(b)
print('*'*8)
print(a.T)

[[0 1 2]
 [3 4 5]]
************
[[0 1]
 [2 3]
 [4 5]]
********
[[0 3]
 [1 4]
 [2 5]]


In [122]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [123]:
a1 = np.arange(12).reshape(3,4)
b1 = np.arange(12,24).reshape(3,4)

In [124]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
b1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [130]:
np.concatenate((a1,b1),axis=0) # concatinating columnwise

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [132]:
np.concatenate((a1,b1),axis=1)

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [134]:
np.hstack((a1,b1))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [135]:
np.vstack((a1,b1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# PANDAS 

In [136]:
import pandas as pd

In [140]:
products = ['A','B','C','D']
prod_categories = pd.Series(products)
prod_categories

0    A
1    B
2    C
3    D
dtype: object

In [143]:
type(prod_categories)

pandas.core.series.Series

In [145]:
start_date_deposit = pd.Series({
    '7/2/24':2000,
    '4/5/24':5000,
    '8/6/24':24000
})

start_date_deposit

7/2/24     2000
4/5/24     5000
8/6/24    24000
dtype: int64

In [146]:
start_date_deposit.min()

2000

In [147]:
start_date_deposit.sum()

31000

In [148]:
start_date_deposit.idxmax()

'8/6/24'

In [149]:
start_date_deposit.idxmin()

'7/2/24'

In [150]:
array_a = np.array([[3,2,1],[6,3,2]])

array_a

array([[3, 2, 1],
       [6, 3, 2]])

In [151]:
array_a = pd.DataFrame([[3,2,1],[6,3,2]])
array_a

0  1  2
0  3  2  1
1  6  3  2

In [154]:
pd.DataFrame([[3,2,1],[6,3,2]],columns=['column1','column2','column3'])

column1  column2  column3
0        3        2        1
1        6        3        2

In [156]:
df = pd.read_csv('Lending-company.csv')
df

LoanID     StringID    Product CustomerGender     Location    Region  \
0          1     LoanID_1  Product B         Female   Location 3  Region 2   
1          2     LoanID_2  Product D         Female   Location 6  Region 6   
2          3     LoanID_3  Product B           Male   Location 8  Region 3   
3          4     LoanID_4  Product A           Male  Location 26  Region 2   
4          5     LoanID_5  Product B         Female  Location 34  Region 3   
...      ...          ...        ...            ...          ...       ...   
1038    1039  LoanID_1039  Product B           Male  Location 73  Region 6   
1039    1040  LoanID_1040  Product A           Male  Location 82  Region 1   
1040    1041  LoanID_1041  Product A   NotSpecified  Location 11  Region 4   
1041    1042  LoanID_1042  Product B         Female  Location 26  Region 6   
1042    1043  LoanID_1043  Product A   NotSpecified  Location 94  Region 6   

      TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
0        17600.0  04/07/2018     2200         45          365       3221   
1            NaN  02/01/2019     2200         45          365       3161   
2        16600.0  08/12/2016     1000         45          365       2260   
3        17600.0         NaN     2200         45          365       3141   
4        21250.0  28/10/2017     2200         55          365       3570   
...          ...         ...      ...        ...          ...        ...   
1038     17300.0  29/12/2018     2200         45          365       3251   
1039         NaN  28/03/2018     2200         45          365       4090   
1040     17300.0  26/04/2018     2200         45          365       4051   
1041     16300.0  25/10/2016     1000         45          365       1930   
1042     17300.0  15/05/2019     2200         45          365       4451   

      AmtPaid60  AmtPaid360        LoanStatus  
0          4166       14621            Active  
1          4096       16041            Active  
2          3205       16340               NaN  
3          4166       16321            Active  
4          4745       14720            Active  
...         ...         ...               ...  
1038       4743       16617  Finished Payment  
1039       5582       16617  Finished Payment  
1040       5143       16617  Finished Payment  
1041       3462       15617  Finished Payment  
1042       4743       16617  Finished Payment  

[1043 rows x 15 columns]

In [157]:
df.index

RangeIndex(start=0, stop=1043, step=1)

In [158]:
df.columns

Index(['LoanID', 'StringID', 'Product', 'CustomerGender', 'Location', 'Region',
       'TotalPrice', 'StartDate', 'Deposit', 'DailyRate', 'TotalDaysYr',
       'AmtPaid36', 'AmtPaid60', 'AmtPaid360', 'LoanStatus'],
      dtype='object')

In [159]:
type(df.columns)

pandas.core.indexes.base.Index

In [160]:
df.dtypes

LoanID              int64
StringID           object
Product            object
CustomerGender     object
Location           object
Region             object
TotalPrice        float64
StartDate          object
Deposit             int64
DailyRate           int64
TotalDaysYr         int64
AmtPaid36           int64
AmtPaid60           int64
AmtPaid360          int64
LoanStatus         object
dtype: object

In [161]:
df.values  # it convert into values 

array([[1, 'LoanID_1', 'Product B', ..., 4166, 14621, 'Active'],
       [2, 'LoanID_2', 'Product D', ..., 4096, 16041, 'Active'],
       [3, 'LoanID_3', 'Product B', ..., 3205, 16340, nan],
       ...,
       [1041, 'LoanID_1041', 'Product A', ..., 5143, 16617,
        'Finished Payment'],
       [1042, 'LoanID_1042', 'Product B', ..., 3462, 15617,
        'Finished Payment'],
       [1043, 'LoanID_1043', 'Product A', ..., 4743, 16617,
        'Finished Payment']], dtype=object)

In [162]:
df.columns.to_numpy()

array(['LoanID', 'StringID', 'Product', 'CustomerGender', 'Location',
       'Region', 'TotalPrice', 'StartDate', 'Deposit', 'DailyRate',
       'TotalDaysYr', 'AmtPaid36', 'AmtPaid60', 'AmtPaid360',
       'LoanStatus'], dtype=object)

### Indexing

In [165]:
# if we want to change the index column

df = pd.read_csv('Lending-company.csv',index_col='StringID')

In [166]:
df

LoanID    Product CustomerGender     Location    Region  \
StringID                                                               
LoanID_1          1  Product B         Female   Location 3  Region 2   
LoanID_2          2  Product D         Female   Location 6  Region 6   
LoanID_3          3  Product B           Male   Location 8  Region 3   
LoanID_4          4  Product A           Male  Location 26  Region 2   
LoanID_5          5  Product B         Female  Location 34  Region 3   
...             ...        ...            ...          ...       ...   
LoanID_1039    1039  Product B           Male  Location 73  Region 6   
LoanID_1040    1040  Product A           Male  Location 82  Region 1   
LoanID_1041    1041  Product A   NotSpecified  Location 11  Region 4   
LoanID_1042    1042  Product B         Female  Location 26  Region 6   
LoanID_1043    1043  Product A   NotSpecified  Location 94  Region 6   

             TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  \
StringID                                                               
LoanID_1        17600.0  04/07/2018     2200         45          365   
LoanID_2            NaN  02/01/2019     2200         45          365   
LoanID_3        16600.0  08/12/2016     1000         45          365   
LoanID_4        17600.0         NaN     2200         45          365   
LoanID_5        21250.0  28/10/2017     2200         55          365   
...                 ...         ...      ...        ...          ...   
LoanID_1039     17300.0  29/12/2018     2200         45          365   
LoanID_1040         NaN  28/03/2018     2200         45          365   
LoanID_1041     17300.0  26/04/2018     2200         45          365   
LoanID_1042     16300.0  25/10/2016     1000         45          365   
LoanID_1043     17300.0  15/05/2019     2200         45          365   

             AmtPaid36  AmtPaid60  AmtPaid360        LoanStatus  
StringID                                                         
LoanID_1          3221       4166       14621            Active  
LoanID_2          3161       4096       16041            Active  
LoanID_3          2260       3205       16340               NaN  
LoanID_4          3141       4166       16321            Active  
LoanID_5          3570       4745       14720            Active  
...                ...        ...         ...               ...  
LoanID_1039       3251       4743       16617  Finished Payment  
LoanID_1040       4090       5582       16617  Finished Payment  
LoanID_1041       4051       5143       16617  Finished Payment  
LoanID_1042       1930       3462       15617  Finished Payment  
LoanID_1043       4451       4743       16617  Finished Payment  

[1043 rows x 14 columns]

In [167]:
df.product

<bound method NDFrame._add_numeric_operations.<locals>.prod of              LoanID    Product CustomerGender     Location    Region  \
StringID                                                               
LoanID_1          1  Product B         Female   Location 3  Region 2   
LoanID_2          2  Product D         Female   Location 6  Region 6   
LoanID_3          3  Product B           Male   Location 8  Region 3   
LoanID_4          4  Product A           Male  Location 26  Region 2   
LoanID_5          5  Product B         Female  Location 34  Region 3   
...             ...        ...            ...          ...       ...   
LoanID_1039    1039  Product B           Male  Location 73  Region 6   
LoanID_1040    1040  Product A           Male  Location 82  Region 1   
LoanID_1041    1041  Product A   NotSpecified  Location 11  Region 4   
LoanID_1042    1042  Product B         Female  Location 26  Region 6   
LoanID_1043    1043  Product A   NotSpecified  Location 94  Region 6   



In [168]:
# Not recomended method
df.Product

StringID
LoanID_1       Product B
LoanID_2       Product D
LoanID_3       Product B
LoanID_4       Product A
LoanID_5       Product B
                 ...    
LoanID_1039    Product B
LoanID_1040    Product A
LoanID_1041    Product A
LoanID_1042    Product B
LoanID_1043    Product A
Name: Product, Length: 1043, dtype: object

In [169]:
# Recommanded method

df['Location']

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...     
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [172]:
df[['Location','Product']]  # to access multiple columns

Location    Product
StringID                           
LoanID_1      Location 3  Product B
LoanID_2      Location 6  Product D
LoanID_3      Location 8  Product B
LoanID_4     Location 26  Product A
LoanID_5     Location 34  Product B
...                  ...        ...
LoanID_1039  Location 73  Product B
LoanID_1040  Location 82  Product A
LoanID_1041  Location 11  Product A
LoanID_1042  Location 26  Product B
LoanID_1043  Location 94  Product A

[1043 rows x 2 columns]

In [174]:
# another way of indexing is .iloc[] or .loc()


df.iloc[4]

LoanID                      5
Product             Product B
CustomerGender         Female
Location          Location 34
Region               Region 3
TotalPrice            21250.0
StartDate          28/10/2017
Deposit                  2200
DailyRate                  55
TotalDaysYr               365
AmtPaid36                3570
AmtPaid60                4745
AmtPaid360              14720
LoanStatus             Active
Name: LoanID_5, dtype: object

In [176]:
df.iloc[[3,4,10]]

LoanID    Product CustomerGender     Location    Region  \
StringID                                                             
LoanID_4        4  Product A           Male  Location 26  Region 2   
LoanID_5        5  Product B         Female  Location 34  Region 3   
LoanID_11      11  Product B         Female  Location 13  Region 6   

           TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
StringID                                                                        
LoanID_4      17600.0         NaN     2200         45          365       3141   
LoanID_5      21250.0  28/10/2017     2200         55          365       3570   
LoanID_11     17600.0  01/05/2018     2200         45          365       3260   

           AmtPaid60  AmtPaid360 LoanStatus  
StringID                                     
LoanID_4        4166       16321     Active  
LoanID_5        4745       14720     Active  
LoanID_11       4405       17380     Active

In [182]:
df.iloc[5:9,::2]

LoanID CustomerGender    Region   StartDate  DailyRate  AmtPaid36  \
StringID                                                                      
LoanID_6       6           Male  Region 1  19/04/2019         45       3301   
LoanID_7       7           Male       NaN  04/07/2020         55       1951   
LoanID_8       8           Male  Region 5  24/04/2018         45       4071   
LoanID_9       9           Male  Region 6  03/09/2019         55       5850   

          AmtPaid360  
StringID              
LoanID_6       15141  
LoanID_7       18701  
LoanID_8       16351  
LoanID_9       21250

In [183]:
df.loc['LoanID_4']

LoanID                      4
Product             Product A
CustomerGender           Male
Location          Location 26
Region               Region 2
TotalPrice            17600.0
StartDate                 NaN
Deposit                  2200
DailyRate                  45
TotalDaysYr               365
AmtPaid36                3141
AmtPaid60                4166
AmtPaid360              16321
LoanStatus             Active
Name: LoanID_4, dtype: object

In [185]:
df.loc[['LoanID_4','LoanID_9']]

LoanID    Product CustomerGender      Location    Region  \
StringID                                                             
LoanID_4       4  Product A           Male   Location 26  Region 2   
LoanID_9       9  Product A           Male  Location 156  Region 6   

          TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
StringID                                                                       
LoanID_4     17600.0         NaN     2200         45          365       3141   
LoanID_9     23250.0  03/09/2019     5000         55          365       5850   

          AmtPaid60  AmtPaid360 LoanStatus  
StringID                                    
LoanID_4       4166       16321     Active  
LoanID_9       7375       21250        NaN